# Generated by Django 2.0.3 on 2019-10-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price_s', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price for Small meal')),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price for Large meal')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal')),
            ],
            bases=('menu.meal',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal')),
            ],
            bases=('menu.meal',),
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal')),
                ('toppings_quantity', models.IntegerField(blank=True, null=True)),
            ],
            bases=('menu.meal',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal')),
            ],
            bases=('menu.meal',),
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal')),
                ('toppings_quantity', models.IntegerField(blank=True, null=True)),
            ],
            bases=('menu.meal',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('meal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal')),
                ('toppings_are_available', models.BooleanField()),
                ('extra_cheese_available', models.BooleanField(default=True)),
            ],
            bases=('menu.meal',),
        ),
        migrations.AlterIndexTogether(
            name='meal',
            index_together={('id', 'slug')},
        ),
    ]
