# Generated by Django 2.0.3 on 2019-09-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='pizza_toppings_quantity',
        ),
    ]
