# Generated by Django 2.0.3 on 2019-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_meal_pizza_toppings_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='pizza_toppings_quantity',
            field=models.IntegerField(blank='True', null='True'),
        ),
    ]
