# Generated by Django 2.0.3 on 2019-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_meal_pizza_toppings_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
