# Generated by Django 2.0.3 on 2019-09-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_topping_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
                ('toppings_quantity', models.IntegerField(blank='True', null='True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
                ('toppings_quantity', models.IntegerField(blank='True', null='True')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
                ('toppings_are_available', models.BooleanField(default='False')),
                ('extra_cheese', models.BooleanField(default='False')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='PizzaTopping',
        ),
        migrations.AlterIndexTogether(
            name='meal',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.AddField(
            model_name='sub',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_related', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicilianpizza_related', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='salad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad_related', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularpizza_related', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_related', to='menu.Category'),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinnerplatter_related', to='menu.Category'),
        ),
        migrations.AlterIndexTogether(
            name='sub',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='sicilianpizza',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='salad',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='regularpizza',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='pasta',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='dinnerplatter',
            index_together={('id', 'slug')},
        ),
    ]
