# Generated by Django 2.0.3 on 2019-09-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20190920_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_l', models.DecimalField(blank='True', decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'categorie'},
        ),
        migrations.AlterIndexTogether(
            name='dinnerplatter',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='pasta',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='regularpizza',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='salad',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='sicilianpizza',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='sub',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_related', to='menu.Category'),
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='category',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price_l',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='slug',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='meal_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='meal_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='meal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salad',
            name='meal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='meal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='meal_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.Meal'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='meal',
            index_together={('id', 'slug')},
        ),
    ]
