# Generated by Django 2.0.3 on 2019-09-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20190920_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
