# Generated by Django 2.0.3 on 2019-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20190920_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price for Large meal if exists'),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='toppings_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='toppings_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub',
            name='toppings_are_available',
            field=models.BooleanField(),
        ),
    ]
