# Generated by Django 2.0.3 on 2019-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20190920_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(default='%(class)s', max_length=100),
        ),
    ]
