# Generated by Django 2.0.3 on 2019-09-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20190920_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(default='type', max_length=100),
        ),
    ]
