# Generated by Django 2.0.3 on 2019-09-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20190920_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
    ]
