# Generated by Django 2.0.3 on 2019-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_remove_meal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='extra_cheese',
        ),
        migrations.AddField(
            model_name='sub',
            name='extra_cheese_available',
            field=models.BooleanField(default=True),
        ),
    ]
