# Generated by Django 2.0.3 on 2019-09-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_auto_20190920_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price for Large meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price for Small meal'),
        ),
    ]
