# Generated by Django 2.0.3 on 2019-09-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20190920_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopping',
            name='price',
        ),
    ]
