# Generated by Django 2.0.5 on 2019-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
