# Generated by Django 2.0.3 on 2019-09-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20190910_1316'),
        ('orders', '0002_auto_20190910_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='OrderItem',
        ),
    ]
