# Generated by Django 2.0.3 on 2019-09-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190910_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='as', max_length=50),
            preserve_default=False,
        ),
    ]
