# Generated by Django 2.0.3 on 2019-09-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190912_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAdditive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additive', to='orders.OrderItem')),
            ],
        ),
    ]
