# Generated by Django 2.0.3 on 2019-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitemadditive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemadditive',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='meal',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meal_description',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItemAdditive',
        ),
    ]
