# Generated by Django 2.0.5 on 2019-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderedtopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedtopping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
