# Generated by Django 2.0.5 on 2019-07-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cart_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('extra_cheese_on_any_sub', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(max_length=64)),
                ('toppings_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small')], max_length=10)),
                ('category', models.CharField(choices=[('Regular', 'Regular Pizza'), ('Sicilian', 'Sicilian Pizza'), ('Salad', 'Salad'), ('Pasta', 'Pasta'), ('Subs', 'Subs'), ('Dinner', 'Dinner Platters')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedMeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Meal')),
                ('toppings', models.ManyToManyField(blank=True, related_name='_orderedmeal_toppings_+', to='orders.OrderedTopping')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderedpizza',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderedpizza',
            name='toppings',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='orders.OrderedMeal'),
        ),
        migrations.DeleteModel(
            name='OrderedPizza',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
