# Generated by Django 2.0.5 on 2019-07-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190702_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='extra_cheese_on_any_sub',
            new_name='is_sub',
        ),
    ]
