# Generated by Django 2.0.5 on 2019-07-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190702_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='is_sub',
            new_name='add_cheese_field',
        ),
        migrations.AddField(
            model_name='meal',
            name='price_l',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
