# Generated by Django 2.0.5 on 2019-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190702_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
