# Generated by Django 2.0.5 on 2019-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_subtopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='size',
            field=models.CharField(blank=True, choices=[('L', 'Large'), ('S', 'Small')], max_length=10, null=True),
        ),
    ]
