# Generated by Django 2.0.5 on 2019-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190702_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmeal',
            name='add_cheese_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='size',
            field=models.CharField(default='Large', max_length=5),
            preserve_default=False,
        ),
    ]
