# Generated by Django 2.0.5 on 2019-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190703_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='size',
            field=models.CharField(blank=True, choices=[('L', 'Large'), ('S', 'Small')], editable=False, max_length=10, null=True),
        ),
    ]
