# Generated by Django 2.0.5 on 2019-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20190703_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='add_cheese_field',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price of Large (if exist)'),
        ),
    ]
