# Generated by Django 2.0.5 on 2019-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190703_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedmeal',
            old_name='add_cheese_field',
            new_name='add_cheese',
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price of Large meal (if exist)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='toppings_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantity of toppings (if exist)'),
        ),
    ]
