# Generated by Django 2.0.3 on 2019-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190703_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmeal',
            name='name',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
